// <auto-generated />
namespace HboFactFind.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedJointFinanciesToPageSix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedJointFinanciesToPageSix));
        
        string IMigrationMetadata.Id
        {
            get { return "201503301411177_Added Joint Financies To Page Six"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
