// <auto-generated />
namespace HboFactFind.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixedIncorrectSpelling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedIncorrectSpelling));
        
        string IMigrationMetadata.Id
        {
            get { return "201503301603566_Fixed Incorrect Spelling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
