// <auto-generated />
namespace HboFactFind.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddednotesforPageOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddednotesforPageOne));
        
        string IMigrationMetadata.Id
        {
            get { return "201503301510203_Added notes for Page One"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
